name: gmvc
env: prod


server:
    host: "0.0.0.0"
    port: 80

template:
    dir: templates/
    ext: html


session:
    prefix: session/
    domain: /
    keyname: gmvcsession
    expires: 30
    redis:
        ip: 192.168.1.31
        port: 6379
        timeout: 3


redis:
    main:
        ip: 192.168.1.31
        port: 6379
        timeout: 3



db:
    default:
        type: mysql
        dsn: root:d@(192.168.9.3:3306)/tank?parseTime=true&charset=utf8&loc=Local
